### ISSUE TITLE
[Renderer - Interactions] NPE when selecting a Comment/Constraint node

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipsesource/papyrus-gefx#12]
The following NPE is thrown when trying to select a Comment or Constraint node:

`java.lang.NullPointerException
	at org.eclipse.gef.mvc.fx.parts.AbstractFeedbackPart.doDetachFromAnchorageVisual(AbstractFeedbackPart.java:116)
	at org.eclipse.gef.mvc.fx.parts.AbstractVisualPart.detachFromAnchorage(AbstractVisualPart.java:377)
	at org.eclipse.gef.mvc.fx.parts.AbstractVisualPart.detachFromAnchorage(AbstractVisualPart.java:355)
	at org.eclipse.gef.mvc.fx.behaviors.AbstractBehavior.removeAnchoreds(AbstractBehavior.java:563)
	at org.eclipse.gef.mvc.fx.behaviors.AbstractBehavior.removeFeedback(AbstractBehavior.java:636)
	at org.eclipse.gef.mvc.fx.behaviors.AbstractBehavior.removeFeedback(AbstractBehavior.java:587)
	at org.eclipse.gef.mvc.fx.behaviors.AbstractBehavior.removeFeedback(AbstractBehavior.java:603)
	at org.eclipse.gef.mvc.fx.behaviors.SelectionBehavior.removeFeedbackAndHandles(SelectionBehavior.java:146)
	at org.eclipse.gef.mvc.fx.behaviors.SelectionBehavior$1.onChanged(SelectionBehavior.java:60)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)`

To be investigated...

**Comment by CamilleLetavernier** [comment]
The Comment uses a weird combination of figures to draw itself. Reworking the shapes (In the context of Issue #9) should solve the issue.
